### ISSUE TITLE
build failure (caused by modern libavcodec?)

### ISSUE THREAD

**Issue by mschilli87** [magnickolas/iosmic#1]
Trying to build on Ubuntu 26.04 I ran into the following:

```
/path/to/iosmic/src/ffmpeg_decode.cc: In member function ‘int FFMpegDecoder::init(uint8_t*, AVCodecID)’:
/path/to/iosmic/src/ffmpeg_decode.cc:33:24: error: ‘FF_PROFILE_AAC_LOW’ was not declared in this scope; did you mean ‘AV_PROFILE_AAC_LOW’?
   33 |     decoder->profile = FF_PROFILE_AAC_LOW;
      |                        ^~~~~~~~~~~~~~~~~~
      |                        AV_PROFILE_AAC_LOW
gmake[2]: *** [CMakeFiles/iosmic.dir/build.make:121: CMakeFiles/iosmic.dir/src/ffmpeg_decode.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/iosmic.dir/all] Error 2
```

My best guess is that something changed in libavcodec since iosmic was developed.

**Comment by magnickolas** [comment]
Hi! I was actually reworking iosmic about 3 months ago to be more stable and standalone (and unarchived this repo prematurely but then got busy with other things). Your message reminded me to do a little polish and publish it, so it's now here. It's in Rust instead of C++ and can be installed as a crate as well as building from source.

You can try to use it and if you do, feel free to report any issues.

**Comment by mschilli87** [comment]
Nice. I can confirm the crate works for me. Just as advertised. Thank you for the good work. ❤️
